-- Update deal dates from Excel
UPDATE alveo_deals SET deal_date = '2025-09-18' WHERE client_name = 'Lina Amenu Poirier' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-09-26' WHERE client_name = 'Préscillia Paquette' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-09-27' WHERE client_name = 'Ghislaine Ahoua' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-06' WHERE client_name = 'Fariyal Habibi Nizamuddin' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-08' WHERE client_name = 'Elizabeth Romero' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-13' WHERE client_name = 'Eva Del Pilar Castillo Franco' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-12' WHERE client_name = 'Providence Mozoba' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-17' WHERE client_name = 'Gabrielle Roussel' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-19' WHERE client_name = 'Yvette ISHIMWE' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-21' WHERE client_name = 'Bryzeida Segovia' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-23' WHERE client_name = 'Élisabeth Turgeon' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-23' WHERE client_name = 'Mbayna Djiba' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-23' WHERE client_name = 'Lily Rose Joly' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-28' WHERE client_name = 'Natacha Petiquay Michaud' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-11-29' WHERE client_name = 'Sabrina Preval Gentile' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-12-04' WHERE client_name = 'Laurence Perrault' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-12-06' WHERE client_name = 'Anastassia Belen Azocar Matus' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-12-08' WHERE client_name = 'Alexandra Proulx' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-12-10' WHERE client_name = 'Kristina Bellavance' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2025-12-23' WHERE client_name = 'Marie Luiny Torchon' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-08' WHERE client_name = 'Jessica Savoie' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-08' WHERE client_name = 'Ashley Constanza' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-10' WHERE client_name = 'Karolane Aubé-Chagnon' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-12' WHERE client_name = 'Sarah Aissani' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-12' WHERE client_name = 'Marie-Joelle Plante' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-16' WHERE client_name = 'Camille Ippersiel' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-16' WHERE client_name = 'Melody Garceau' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-18' WHERE client_name = 'Faravena Olivier' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-24' WHERE client_name = 'Doungbissi Riovanna' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-27' WHERE client_name = 'Fidèle Aka' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-01-29' WHERE client_name = 'Ashley Dare' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-02-09' WHERE client_name = 'Cloé Sirois' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-02-25' WHERE client_name = 'Tamara Galante' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-02-26' WHERE client_name = 'Maika Jourdenais' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-05' WHERE client_name = 'Amélie Cloutier' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-06' WHERE client_name = 'Ayanha Lepage' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-09' WHERE client_name = 'Samantha-Lee Gervais Plante' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-10' WHERE client_name = 'Angy Clenor' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-15' WHERE client_name = 'Raphaëlle Renaud' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-03-18' WHERE client_name = 'Charlotte Vigeant' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-04-01' WHERE client_name = 'Kim Goupil' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-07' WHERE client_name = 'Anabella Hamel' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-12' WHERE client_name = 'Clairefée Andréma Castro Clairvoyant' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-14' WHERE client_name = 'Sandrine Melancon' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-15' WHERE client_name = 'Lenina Guertin' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-16' WHERE client_name = 'Vanessa Couture' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-19' WHERE client_name = 'Priscilla Bestial' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-19' WHERE client_name = 'Amanda Lavallée' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-21' WHERE client_name = 'Marjorie Dufresne' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-22' WHERE client_name = 'Aya Azizi' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-28' WHERE client_name = 'Khayla Chartier' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-29' WHERE client_name = 'Kelly Desrosiers' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-05-30' WHERE client_name = 'Karen Ng Foong Lin' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-03' WHERE client_name = 'Felicity Amoah' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-18' WHERE client_name = 'Chahineze' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-21' WHERE client_name = 'Rose Zeagman' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-22' WHERE client_name = 'Elsa Miklosic' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-23' WHERE client_name = 'Daphne Berthiaume' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-24' WHERE client_name = 'Claudia Habib' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-26' WHERE client_name = 'Sabrina Ireland' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-26' WHERE client_name = 'Jessica St-Pierre' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-26' WHERE client_name = 'Christiane Vallée' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-06-29' WHERE client_name = 'Noémie Trempe' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-07-02' WHERE client_name = 'Tania Levesque' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-07-04' WHERE client_name = 'Joanie Simard' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-07-06' WHERE client_name = 'Annaelle Fiette' AND deal_date IS NULL;
UPDATE alveo_deals SET deal_date = '2026-07-07' WHERE client_name = 'Laurence Jauvin' AND deal_date IS NULL;